### ISSUE TITLE
PocketCasts stayed open but paused overnight - my calendar has events for today and yesterday

### ISSUE THREAD

**Issue by eli-b** [yuvaldrori/Forty#1]
PocketCasts stayed open but paused overnight, and now my calendar has podcast-events for today and yesterday. I only listened to the podcast yesterday, not today.

Forty should only create calendar podcast-events for a day if I actually played the podcast on that day.

**Comment by yuvaldrori** [comment]
I currently use all app notifications except the downloading notification to mark a listening session. Since the app was open before 00:00, it probably sent a "Pause" notification when it closed the day after, thus adding the session to the calendar. If I only listen to "Play" notifications, if the app was playing before 00:00 and stopped after, then the session would not register the next day. I opted to fix this problem (probably because I wrote this code at around 00:00). You can delete the session event from your calendar if you do not resume the podcast at another time later that day.
Let me know if you think of a better way to do this.
